<?php

/**
 * @file
 * Culturefeed content module file.
 */

/**
 * Implements hook_theme().
 */
function culturefeed_content_theme() {
  $theme = [];

  $theme['culturefeed_content_formatter'] = [
    'variables' => [
      'items' => [],
      'view_mode' => NULL,
      'title' => NULL,
      'more_link' => NULL,
      'pager' => NULL,
    ],
    'file' => 'includes/theme.inc',
  ];

  return $theme;
}

/**
 * Add Google Tag Manager script tags just below the page HEAD.
 *
 * Implements hook_page_top().
 */
function culturefeed_content_page_top(array &$page_top) {

  $apiConfig = \Drupal::config('culturefeed_api.settings');
  $siteConfig = \Drupal::config('system.site');
  $currentUser = \Drupal::currentUser();
  $cultureFeedCurrentUser = \Drupal::service('culturefeed_user.current_user');
  $moduleHandler = \Drupal::service('module_handler');

  $container_id = 'GTM-WPZSG2';
  $langcode = Drupal::languageManager()->getCurrentLanguage()->getId();

  // Check if it is a search page.
  if ($moduleHandler->moduleExists('culturefeed_agenda')) {
    $gtm_globals['is_agenda_search'] = \Drupal::routeMatch()->getRouteName() == 'culturefeed_agenda.agenda';
  }
  else {
    $gtm_globals['is_agenda_search'] = FALSE;
  }

  if ($gtm_globals['is_agenda_search']) {
    $gtm_globals['search_query'] = json_encode(Drupal::request()->query->all());
  }

  // Check if it is a detail page.
  $gtm_globals['is_detail'] = \Drupal::routeMatch()->getRouteName() == 'culturefeed_agenda.event_detail';
  if ($gtm_globals['is_detail']) {

    // Make this backwards compatible.
    $gtm_globals['is_event_detail'] = TRUE;

    /** @var CultuurNet\SearchV3\ValueObjects\Event $event */
    $event = \Drupal::routeMatch()->getParameter('event');
    $gtm_globals['detail_title'] = $event->getName()->getValueForLanguage($langcode);
    $gtm_globals['detail_type'] = 'event';
    $gtm_globals['cdbid'] = $event->getCdbid();
  }

  // Add custom dimensions.
  $gtm_globals['consumer_key'] = $apiConfig->get('application_key');
  $gtm_globals['consumer_name'] = $siteConfig->get('name');
  $gtm_globals['login_status'] = $currentUser->isAuthenticated();

  $gtm_globals['user_id'] = '';
  if ($cultureFeedCurrentUser->isCultureFeedUser()) {
    $gtm_globals['user_id'] = $cultureFeedCurrentUser->getUserId();
  }

  // Set the script code.
  // Add global variables.
  $gtm_datalayer = 'dataLayer = [' . json_encode($gtm_globals) . '];';

  // GTM Code.
  $gtm_iframe = '<iframe src="//www.googletagmanager.com/ns.html?id=' . $container_id . '"';
  $gtm_iframe .= 'height="0" width="0" style="display:none;visibility:hidden"></iframe>';

  $gtm_snippet = '(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':';
  $gtm_snippet .= 'new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],';
  $gtm_snippet .= 'j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=';
  $gtm_snippet .= '\'//www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);';
  $gtm_snippet .= '})(window,document,\'script\',\'dataLayer\',\'' . $container_id . '\');';

  $page_top['cf_google_tag_manager_datalayer'] = [
    '#type' => 'html_tag',
    '#tag' => 'script',
    '#value' => $gtm_datalayer,
    '#prefix' => '<!-- Google Tag Manager -->',
  ];

  $page_top['cf_google_tag_manager_iframe'] = [
    '#type' => 'html_tag',
    '#tag' => 'noscript',
    '#value' => $gtm_iframe,
  ];

  $page_top['cf_google_tag_manager_snippet'] = [
    '#type' => 'html_tag',
    '#tag' => 'script',
    '#value' => $gtm_snippet,
    '#suffix' => '<!-- End Google Tag Manager -->',
  ];
}
