<?php

/**
 * @file
 * Culturefeed content module file.
 */

/**
 * Implements hook_theme().
 */
function culturefeed_content_theme() {
  $theme = [];

  $theme['culturefeed_content_formatter'] = [
    'variables' => [
      'items' => [],
      'view_mode' => NULL,
      'title' => NULL,
      'more_link' => NULL,
      'pager' => NULL,
    ],
    'file' => 'includes/theme.inc',
  ];

  return $theme;
}
